[package]
name = "sigstore-risc0-methods"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
risc0-build = { version = "^3.0.3", features = ["unstable"]}

[package.metadata.risc0]
methods = ["guest"]